#=================================================
# https://github.com/danxiaonuo/sing-box-docker
# Lisence: MIT
# Author: danxiaonuo
# Blog: https://www.danxiaonuo.com
#=================================================

name: 自动编译并上传镜像

# 设置触发条件
on:
  # 仓库触发工作流
  repository_dispatch:
  # 编辑文件触发开始编译
  push:
    paths:
      - 'Dockerfile'
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      build:
        description: 'build sing-box'
        required: true
        default: 'build sing-box'
  # 定时触发编译(每天早5点)
  schedule:
     - cron: '0 21 * * *'
 # 点☆Star触发开始编译
  watch:  
     types: [started]
     
 # 任务集
jobs:
  build:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_TAG: latest
    
    # 运行步骤
    steps:
    
    # 检出master分支
    - name: 检出各个模块代码
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 安装 QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: 安装 docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

    - name: 登录 DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: 构建镜像并发布
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sing-box:${{ matrix.DOCKER_TAG }}
      
    - name: 上传至阿里云
      id: buildAndPushImage
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: 'registry.cn-hongkong.aliyuncs.com'
        namespaces: 'danxiaonuo'
        repository_name: 'sing-box'
        user_name: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}
        image_version: ${{ matrix.DOCKER_TAG }}
        docker_file: '.'
            
    - name: 删除旧的GitHub-workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 1    #保留多少个workflow不删除
